<script src="js/slider.js"></script>

<main>
  
  
  
    <div class="parallax-container">
          <div class="parallax"><img src="images/fondecran.jpg" alt="mur"></div>

    </div>  

    <section id="mesCompetences">

      <h3>Mes Compétences</h3>
      
      <div class="carousel">
        <a class="carousel-item" href="#one!"><img src="images/html5.jpg" alt="htmllogo"></a>
        <a class="carousel-item" href="#two!"><img src="images/css3.jpg" alt="csslogo"></a>
        <a class="carousel-item" href="#three!"><img src="images/JS.png" alt="jslogo"></a>
        <a class="carousel-item" href="#four!"><img src="images/PHP.jpg" alt="phplogo"></a>
        <a class="carousel-item" href="#six!"><img src="images/mysql.jpg" alt="mysqllogo"></a>
        <a class="carousel-item" href="#seven!"><img src="images/symfony.jpg" alt="symfonylogo"></a>
        <a class="carousel-item" href="#eight!"><img src="images/jQuery.jpg" alt="jquerylogo"></a>
        <a class="carousel-item" href="#ten!"><img src="images/materialize.jpg" alt="materializelogo"></a>
        <a class="carousel-item" href="#eleven!"><img src="images/bootstrap.jpg" alt="bootstraplogo"></a>
        <a class="carousel-item" href="#twelve!"><img src="images/wordpress.jpg" alt="wordpresslogo"></a>
        <a class="carousel-item" href="#thirteen!"><img src="images/responsive.png" alt="responsivelogo"></a>
        <a class="carousel-item" href="#fourteen!"><img src="images/photoshop.svg" alt="photoshoplogo"></a>
      </div>

    </section> 


     <div class="parallax-container">
          <div class="parallax"><img src="images/fondecran.jpg" alt="mur"></div>

    </div>


    <h3 id="parcours">Mon Parcours</h3>

    <section id="monParcours">

      


          <div id="timeline">
    <ul id="dates">
      <li><a href="#2003">2003</a></li>
      <li><a href="#2004">2004</a></li>
      <li><a href="#2005">2005</a></li>
      <li><a href="#2006">2006</a></li>
      <li><a href="#2016">2016</a></li>
      <li><a href="#2017">2017</a></li>
    </ul>

    <ul id="issues">

      <li id="2003">
        <img src="images/diplome.png" width="256" height="256" alt="diplome" />
        <h4>2003</h4>
        <p>BTS GESTION ET MERCATIQUE HOTELLIERE</p>
      </li>

      <li id="2004">
        <img src="images/receptionniste.jpg" width="256" height="256" alt="receptionniste"/>
        <h4>2004</h4>
        <p>1er EMPLOI dans l'hôtellerie : RECEPTIONNISTE</p>
      </li>

      <li id="2005">
          <img src="images/manager.jpg" width="256" height="256" alt="manager" />
        <h4>2005</h4>
        <p>On continue dans l'hôtellerie mais je prends du galon : Chef de réception</p>
      </li>

      <li id="2006">
          <img src="images/PC.jpg" width="256" height="256" alt="pc" />
        <h4>2006</h4>
        <p>L'heure du changement : me voilà démarrant un nouveau métier, presque par hasard : TECHNICIEN SUPPORT pour les métiers de l'hôtellerie et de la restauration.</p>
        <p>Mais quésako ?</p>
        <p>je suis là pour aider les utilisateurs de nos logiciels, servant exclusivement en restauration, vous savez les petits écrans pleins de couleurs qu'utilisent les serveurs quand vous allez au restaurant. Ou encore pour les hôtelliers.</p>
        <p>En quelque sorte un technicien support est un sauveur !! oui oui un sauveur, surtout en plein service avec tous les clients autours du pauvre serveur qui n'arrive pas à saisir sa note !</p>
      </li>

      <li id="2016">
          <img src="images/site-internet.jpg" width="256" height="256" alt="arobase"/>
        <h4>2016</h4>
        <p>Et là, PAF c'est le drame ! Non pas complétement, je m'explique:</p>
        <p>Licenciement économique....horreur, malheurs !!</p>
        <p>Et bien NON ! Il s'agit plutôt d'une renaissance professionelle, je vais me rapprocher un peu plus de ce que j'aime. Non pas que je n'appreciais pas mon précèdent métier mais à partir de maintenant on va CREER !!!</p>
        <p>Me voilà donc partie avec mes petits cahiers et mes crayons de couleurs : FORMATION DEVELOPPEUR ET INTEGRATEUR WEB !</p>
      </li>


      <li id="2017">
          <img src="images/logo_formation.jpg" width="256" height="256" alt="formation" />
        <h4>2017</h4>
        <p>Histoire de se perfectionner, on continue avec la formation sur le framework PHP : SYMFONY.</p>
        <p>Et pour donner bonne "image" (jeu de mots, merci merci), je fignole avec une formation PHOTOSHOP</p>
      </li>

      
    </ul>
    
  </div>



   </section>

  <section id="monParcours2">

    <article>

    <h4 id="date"></h4>

    <img id="image" src="" alt="photoparcours">
    
    <p id="texteParcours"></p>
        
    </article>

    <button id="avant"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i></button>
    <button id="apres"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></button>

  </section>
    
  
    
    

  

   
 <div class="parallax-container">
          <div class="parallax"><img src="images/fondecran.jpg" alt="mur"></div>

    </div>

    <section id="projets">

    <h3>Portfolio</h3>
    
   <?php foreach ($projets as $projet) : ?>


	<div class="projet">
	
	<h4><?= htmlspecialchars($projet['titre']) ;?></h4>

	

	<div class="monimage">
	<a href="<?= ($projet['lienSite']) ;?>"><img class="projetImg" src="images/projets/<?= ($projet['Images']) ;?>" alt="image"/></a>
	</div>


	<p><?= htmlspecialchars($projet['langages']) ;?></p>

	</div>

<?php endforeach;?>


    </section>

  
  
 </main>

 