<!doctype html>
 <html lang="fr">

 <head>
 <meta charset="utf-8"/>
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="css/reset.css"/>
 
 <script
        src="https://code.jquery.com/jquery-3.1.1.js"
        integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
        crossorigin="anonymous"></script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

<script src="js/jquery.timelinr-0.9.6.js"></script>


<link rel="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css" integrity="sha384-dNpIIXE8U05kAbPhy3G1cz+yZmTzA6CY8Vg/u2L9xRnHjJiAK76m2BIEaSEV+/aU" crossorigin="anonymous">

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">


<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">

<!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>




<link href="https://fonts.googleapis.com/css?family=Damion" rel="stylesheet"> 
 <link rel="stylesheet" href="css/style.css"/>


<title>Cécile Besnard, Développeur, Integrateur Web</title>

<meta name="description" content="Je suis développeur et intégrateur Web. Je travail avec HTML, CSS, JS, PHP, SQL et des outils comme Symfony, jQuery, Materialize pour la création de site internet." />
<link rel="icon" href="images/website.png" />




</head>
<body>
    
 <header>
   <span style="font-size:30px;cursor:pointer"><i class="fa fa-bars openNav" aria-hidden="true"></i>
</span>
   <div id="mySidenav" class="sidenav">
     <span class="closebtn">&times;</span>
     <a href="#mesCompetences" data-encre="#mesCompetences" class="closenav">Mes Compétences</a>
     <a href="#parcours" class="closenav" data-encre="#parcours">Mon Parcours</a>
     <a href="#projets" class="closenav" data-encre="#projets">PortFolio</a>
     <a href="#contact" class="closenav" data-encre="#contact">Contact</a>
   </div>
   
     
  <div><a id="retour" href="#"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></div>
  
  
   <h1 id="mainTitle">Intégrateur, Développeur WEB</h1>

    <h2 id="name">Cécile Besnard</h2>
       

  
 </header>
 

 <?php include $template.'.phtml';?>
 
    
 <footer>
     
     <h2>N'hésitez pas à me contacter : </h2>
     
     <form action="mail.php" method="POST" id="contact">
         <p>Votre Nom :</p>
            <input type="text" name="nom" required>
         <p>Votre Email :</p>
            <input type="email" name="email" class="validate" required>
            
            <p>Votre Message :</p>
            <textarea name="message" rows="6" cols="25"  class="validate" required></textarea><br />
    <input type="submit" value="Send">
    </form>
  
   <h2><a class="cv" href="documents/CV.pdf">Pour télécharger mon CV, c'est par Ici...</a></h2>
  
   <ul>
       
        <li><a href="mailto:besnardcecile81@gmail.com"><i class="fa fa-envelope-square" aria-hidden="true"></i></a></li>
        <li><a href="https://www.linkedin.com/in/cecile-besnard-ab076110b"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
        <li><a href="https://github.com/cecilebesnard"><i class="fa fa-github" aria-hidden="true"></i>
</i></a></li>
        
    </ul>
   
   <a href="mentionsLegales.php" id="mentions">Mentions Légales</a>
   <p class="lienMentions">Copyright-Soartweb.fr 2017 - Tous droits réservés.</p>
   

  
  
  
  
 </footer>
    


<script src="js/main.js"></script>


</body>



</html>