<!doctype html>
 <html lang="fr">

 <head>
 <meta charset="utf-8"/>
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="stylesheet" href="css/reset.css"/>
 
 <script
        src="https://code.jquery.com/jquery-3.1.1.js"
        integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
        crossorigin="anonymous"></script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

<script src="js/jquery.timelinr-0.9.6.js"></script>


<link rel="stylesheet" href="https://opensource.keycdn.com/fontawesome/4.7.0/font-awesome.min.css" integrity="sha384-dNpIIXE8U05kAbPhy3G1cz+yZmTzA6CY8Vg/u2L9xRnHjJiAK76m2BIEaSEV+/aU" crossorigin="anonymous">

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">


<!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">

<!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>

<script src="js/slider.js"></script>


<link href="https://fonts.googleapis.com/css?family=Damion" rel="stylesheet"> 
 <link rel="stylesheet" href="css/style.css"/>


<title>Cécile Besnard</title>
<link rel="icon" href="images/icon.ico" />



</head>
<body>
    
 <header>
   <span style="font-size:30px;cursor:pointer" onclick="openNav()"><i class="fa fa-bars" aria-hidden="true"></i>
</span>
   <div id="mySidenav" class="sidenav">
     <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
     <a href="#mesCompetences">Mes Competences</a>
     <a href="#parcours">Mon Parcours</a>
     <a href="#projets">PortFolio</a>
     <a href="#contact">Contact</a>
   </div>
   
     
  <div><a id="retour" href="#mainTitle"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></div>
  
  
   <h1 id="mainTitle">Intégrateur, Développeur WEB</h1>

    <h2 id="name">Cécile Besnard Trano</h2>
       

  
 </header>
 

 <main>
  
  <div id="main">
  
    <div class="parallax-container">
          <div class="parallax"><img src="images/fondecran.jpg"></div>

    </div>  

    <section id="mesCompetences">

      <h3>Mes Competences</h3>
      
      <div class="carousel">
        <a class="carousel-item" href="#one!"><img src="images/html5.jpg"></a>
        <a class="carousel-item" href="#two!"><img src="images/css3.jpg"></a>
        <a class="carousel-item" href="#three!"><img src="images/JS.png"></a>
        <a class="carousel-item" href="#four!"><img src="images/PHP.jpg"></a>
        <a class="carousel-item" href="#six!"><img src="images/mysql.jpg"></a>
        <a class="carousel-item" href="#seven!"><img src="images/symfony.jpg"></a>
        <a class="carousel-item" href="#eight!"><img src="images/jQuery.jpg"></a>
        <a class="carousel-item" href="#ten!"><img src="images/materialize.jpg"></a>
        <a class="carousel-item" href="#eleven!"><img src="images/bootstrap.jpg"></a>
        <a class="carousel-item" href="#twelve!"><img src="images/wordpress.jpg"></a>
        <a class="carousel-item" href="#thirteen!"><img src="images/responsive.png"></a>
        <a class="carousel-item" href="#fourteen!"><img src="images/photoshop.svg"></a>
      </div>

    </section> 


     <div class="parallax-container">
          <div class="parallax"><img src="images/fondecran.jpg"></div>

    </div>


    <h3 id="parcours">Mon Parcours</h3>

    <section id="monParcours">

      


          <div id="timeline">
    <ul id="dates">
      <li><a href="#2003">2003</a></li>
      <li><a href="#2004">2004</a></li>
      <li><a href="#2005">2005</a></li>
      <li><a href="#2006">2006</a></li>
      <li><a href="#2016">2016</a></li>
      <li><a href="#2017">2017</a></li>
    </ul>

    <ul id="issues">

      <li id="2003">
        <img src="images/diplome.png" width="256" height="256" />
        <h4>2003</h4>
        <p>BTS GESTION ET MERCATIQUE HOTELLIERE</p>
      </li>

      <li id="2004">
        <img src="images/receptionniste.jpg" width="256" height="256" />
        <h4>2004</h4>
        <p>1er EMPLOI dans l'hotellerie : RECEPTIONNISTE</p>
      </li>

      <li id="2005">
        <img src="images/manager.jpg" width="256" height="256" />
        <h4>2005</h4>
        <p>On continue dans l'hotellerie mais je prends du galon : Chef de réception</p>
      </li>

      <li id="2006">
        <img src="images/PC.jpg" width="256" height="256" />
        <h4>2006</h4>
        <p>L'heure du changement : me voilà démarrant un nouveau metier, presque par hasard : TECHNICIEN SUPPORT pour les metiers de l'hotellerie et de la restauration.</p>
        <p>Mais quésako ?</p>
        <p>je suis là pour aider les utilisateurs de nos logiciels, servant exclusivement en restauraton, vous savez les petits ecrans pleins de couleurs qu'utilisent les serveurs quand vous allez au restaurant. Ou encore pour les hotelliers.</p>
        <p>En quelque sorte un technicien support est un sauveur !! oui oui un sauveur, surtout en plein services avec tous les clients autour du pauvre serveur qui n'arrive pas à saisir sa note !</p>
      </li>

      <li id="2016">
        <img src="images/site-internet.jpg" width="256" height="256" />
        <h4>2016</h4>
        <p>Et là, PAF c'est le drame ! Non pas completement, je m'explique:</p>
        <p>Licenciement économique....horreur, malheurs !!</p>
        <p>Et bien NON ! Il s'agit plutot d'une renaissance professionelle, je vais me rapprocher un peu plus de ce que j'aime. Non pas que je n'appreciais pas mon précèdent metier mais à partir de maintenant on va CREER !!!</p>
        <p>Me voilà donc partie avec mes petits cahiers et mes crayons de couleurs : FORMATION DEVELOPPEUR ET INTEGRATEUR WEB !</p>
      </li>


      <li id="2017">
        <img src="images/logo_formation.jpg" width="256" height="256" />
        <h4>2017</h4>
        <p>Et histoire de se perfectionner, on continue avec la formation sur le framework PHP : SYMFONY.</p>
        <p>Et pour donner bonne "image" (jeu de mots, merci merci), je fignole avec une formation PHOTOSHOP</p>
      </li>

      
    </ul>
    
  </div>



   </section>

  <section id="monParcours2">

    <article>

    <h4 id="date"></h4>

    <img id="image" src="" alt="photo">
    
    <p id="texteParcours"></p>
        
    </article>

    <button id="avant"><i class="fa fa-arrow-circle-left" aria-hidden="true"></i></button>
    <button id="apres"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></button>

  </section>
    
  
    
    

  

   
 <div class="parallax-container">
          <div class="parallax"><img src="images/fondecran.jpg"></div>

    </div>

    <section id="projets">

    <h3>Portfolio</h3>
    
    <?php include $template.'.phtml';?>


    </section>

  
  </div>
 </main>
 
 
    
 <footer>
     
     <h2>N'hésitez pas à me contacter : </h2>
     
     <form action="mail.php" method="POST" id="contact">
         <p>Votre Nom :</p>
            <input type="text" name="nom">
         <p>Votre Email :</p>
            <input type="text" name="email">
            <p>Votre Message :</p>
            <textarea name="message" rows="6" cols="25"></textarea><br />
    <input type="submit" value="Send">
    </form>
  
   <h2><a class="cv" href="documents/CV.pdf">Pour télécharger mon CV, c'est par Ici...</a></h2>
  
   <ul>
       
        <li><a href="mailto:besnardcecile81@gmail.com"><i class="fa fa-envelope-square" aria-hidden="true"></i></a></li>
        <li><a href="https://www.linkedin.com/in/cecile-besnard-ab076110b"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
        <li><a href="https://github.com/cecilebesnard"><i class="fa fa-github" aria-hidden="true"></i>
</i></a></li>
        
    </ul>
   

  
  
  
  
 </footer>
    


<script src="js/main.js"></script>


</body>



</html>